frontend:
  replicaCount: 1

  image:
    repository: farzaan548/to-do-frontend
    tag: ""
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 80
    


backend:
  replicaCount: 1

  image:
    repository: farzaan548/to-do-backend
    tag: ""
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000


mongo:
  replicaCount: 1

  image:
    repository: mongo
    tag: "7.0"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017

  persistence:
    size: 5Gi
   
    enabled: true
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 5Gi