apiVersion: v1
kind: Service

metadata:
  name: mongo
  namespace: to-do-app
  labels:
    app: mongo

spec:
  selector:
    app: mongo

  

  ports:
    - name: http
      port: 27017
      targetPort: 27017
 
  type: ClusterIP