apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    app: mongo
spec:
  accessModes:
    - {{ .Values.mongo.persistence.accessMode }}
  storageClassName: {{ .Values.mongo.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mongo.persistence.size }}